apiVersion: v1
kind: Pod
metadata:
  name:
  labels:
    app:
spec:
  containers:
  - name:
    image:
    env:
      # learn about the downward api https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api
    - name: HELLO
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    ports:
    - name:
      containerPort:
      protocol: TCP